/**
 * PortfolioSkeleton.jsx
 * Loading skeleton placeholder for portfolio cards.
 * Shown while portfolios are being generated by the AI.
 */
import React from 'react';
import PropTypes from 'prop-types';

/**
 * A single skeleton card placeholder.
 */
function SkeletonCard() {
  return (
    <div
      className="bg-white rounded-2xl border-l-4 border-l-border shadow-card p-6 animate-pulse"
      aria-hidden="true"
    >
      {/* Header */}
      <div className="flex justify-between mb-4">
        <div className="h-5 bg-border rounded-full w-24" />
        <div className="h-5 bg-border rounded-full w-16" />
      </div>

      {/* Title */}
      <div className="flex items-center gap-3 mb-4">
        <div className="w-8 h-8 bg-border rounded-full" />
        <div className="space-y-1.5 flex-1">
          <div className="h-4 bg-border rounded w-3/4" />
          <div className="h-3 bg-border rounded w-1/2" />
        </div>
      </div>

      {/* Track bars */}
      <div className="space-y-3 my-4">
        {[70, 50, 40].map((width, i) => (
          <div key={i}>
            <div className="flex justify-between mb-1.5">
              <div className="h-3 bg-border rounded w-24" />
              <div className="h-3 bg-border rounded w-16" />
            </div>
            <div className="h-2 bg-border rounded-full">
              <div
                className="h-full bg-slate-200 rounded-full"
                style={{ width: `${width}%` }}
              />
            </div>
          </div>
        ))}
      </div>

      {/* Financial summary */}
      <div className="rounded-xl bg-surface p-4 space-y-2.5">
        <div className="flex justify-between">
          <div className="h-4 bg-border rounded w-20" />
          <div className="h-4 bg-border rounded w-24" />
        </div>
        <div className="border-t border-border" />
        <div className="flex justify-between">
          <div className="h-3 bg-border rounded w-16" />
          <div className="h-3 bg-border rounded w-20" />
        </div>
        <div className="flex justify-between">
          <div className="h-3 bg-border rounded w-16" />
          <div className="h-3 bg-border rounded w-20" />
        </div>
      </div>

      {/* Button */}
      <div className="mt-5 h-11 bg-border rounded-lg" />
    </div>
  );
}

/**
 * PortfolioSkeleton - renders N skeleton cards in a grid.
 *
 * @param {number} count - Number of skeleton cards to show
 */
export default function PortfolioSkeleton({ count = 4 }) {
  return (
    <div role="status" aria-label="טוען תיקי משכנתא...">
      {/* Loading message */}
      <div className="text-center mb-8">
        <div className="inline-flex flex-col items-center gap-3">
          {/* Animated logo */}
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary to-blue-500 flex items-center justify-center animate-pulse">
            <span className="text-white font-bold text-lg" aria-hidden="true">M</span>
          </div>
          <p className="text-text2 font-medium">מחשב את התיקים שלך...</p>
          <p className="text-sm text-text3">מנתח נתוני בנק ישראל</p>
        </div>
      </div>

      {/* Skeleton grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        {Array.from({ length: count }, (_, i) => (
          <SkeletonCard key={i} />
        ))}
      </div>
    </div>
  );
}

PortfolioSkeleton.propTypes = {
  count: PropTypes.number,
};
